PGPASSWORD=$POSTGRES_PASSWORD

psql $POSTGRES_DATABASE -U "$POSTGRES_USER" << EOSQL
create role $POSTGRES_USER_UNROOT with login password '$POSTGRES_PASSWORD_UNROOT';
create database $POSTGRES_DATABASE_UNROOT;
grant all privileges on database $POSTGRES_DATABASE_UNROOT to $POSTGRES_USER_UNROOT;
EOSQL
